# **EXERCICE SUR PANDAS : ANALYSE D'UN JEU DE DONNÉES**

In [4]:
# Importer Pandas et Numpy
import pandas as pd
import numpy as np

In [5]:
# Exécutez cette cellule
file = 'https://raw.githubusercontent.com/JosueAfouda/TUTORIALS/main/FuelConsumptionCo2.csv'
# Ce fichier est issu du Github de Josué Afouda. Je vous encourage à aller voir ses cours sur Youtube et son Github.

# Importation des données
df = pd.read_csv(file)

### 1) Affichez les 10 premières lignes du datframe

In [6]:
df.head(10)

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
5,2014,ACURA,RLX,MID-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230
6,2014,ACURA,TL,MID-SIZE,3.5,6,AS6,Z,11.8,8.1,10.1,28,232
7,2014,ACURA,TL AWD,MID-SIZE,3.7,6,AS6,Z,12.8,9.0,11.1,25,255
8,2014,ACURA,TL AWD,MID-SIZE,3.7,6,M6,Z,13.4,9.5,11.6,24,267
9,2014,ACURA,TSX,COMPACT,2.4,4,AS5,Z,10.6,7.5,9.2,31,212

### 2) Affichez les 5 dernières lignes du dataframe ainsi que des info sur le dataframe

In [7]:
df.tail(5)

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
1062,2014,VOLVO,XC60 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1063,2014,VOLVO,XC60 AWD,SUV - SMALL,3.2,6,AS6,X,13.2,9.5,11.5,25,264
1064,2014,VOLVO,XC70 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1065,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,X,12.9,9.3,11.3,25,260
1066,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,X,14.9,10.2,12.8,22,294

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   MODELYEAR                 1067 non-null   int64
 1   MAKE                      1067 non-null   str
 2   MODEL                     1067 non-null   str
 3   VEHICLECLASS              1067 non-null   str
 4   ENGINESIZE                1067 non-null   float64
 5   CYLINDERS                 1067 non-null   int64
 6   TRANSMISSION              1067 non-null   str
 7   FUELTYPE                  1067 non-null   str
 8   FUELCONSUMPTION_CITY      1067 non-null   float64
 9   FUELCONSUMPTION_HWY       1067 non-null   float64
 10  FUELCONSUMPTION_COMB      1067 non-null   float64
 11  FUELCONSUMPTION_COMB_MPG  1067 non-null   int64
 12  CO2EMISSIONS              1067 non-null   int64
dtypes: float64(4), int64(4), str(5)
memory usage: 108.5 KB

### 3) Utilisez la fonction permettant de faire un résumé statistique des données n'incluant que les variables quantitatives

In [9]:
# Faites un résumé statistique des données n'incluant que les variables quantitatives
df.describe()

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
count,1067.0,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,2014.0,3.346298,5.794752,13.296532,9.474602,11.580881,26.441425,256.228679
std,0.0,1.415895,1.797447,4.101253,2.794510,3.485595,7.468702,63.372304
min,2014.0,1.000000,3.000000,4.600000,4.900000,4.700000,11.000000,108.000000
25%,2014.0,2.000000,4.000000,10.250000,7.500000,9.000000,21.000000,207.000000
50%,2014.0,3.400000,6.000000,12.600000,8.800000,10.900000,26.000000,251.000000
75%,2014.0,4.300000,8.000000,15.550000,10.850000,13.350000,31.000000,294.000000
max,2014.0,8.400000,12.000000,30.200000,20.500000,25.800000,60.000000,488.000000

### 4) Déterminez les valeurs distinctes de chaque variable qualitative du dataframe

In [10]:
# Déterminez les valeurs distinctes de chaque variable qualitative de df
variables_qualitatives = df.select_dtypes(include=['object']).columns
for col in variables_qualitatives:
    print(f"Valeurs distinctes pour '{col}' :")
    print(df[col].unique())
    print("-" * 30)

Valeurs distinctes pour 'MAKE' :
<StringArray>
[        'ACURA',  'ASTON MARTIN',          'AUDI',       'BENTLEY',
           'BMW',         'BUICK',      'CADILLAC',     'CHEVROLET',
      'CHRYSLER',         'DODGE',          'FIAT',          'FORD',
           'GMC',         'HONDA',       'HYUNDAI',      'INFINITI',
        'JAGUAR',          'JEEP',           'KIA',   'LAMBORGHINI',
    'LAND ROVER',         'LEXUS',       'LINCOLN',      'MASERATI',
         'MAZDA', 'MERCEDES-BENZ',          'MINI',    'MITSUBISHI',
        'NISSAN',       'PORSCHE',           'RAM',   'ROLLS-ROYCE',
         'SCION',         'SMART',           'SRT',        'SUBARU',
        'TOYOTA',    'VOLKSWAGEN',         'VOLVO']
Length: 39, dtype: str
------------------------------
Valeurs distinctes pour 'MODEL' :
<StringArray>
[                     'ILX',               'ILX HYBRID',
                  'MDX 4WD',                  'RDX AWD',
                      'RLX',                       'TL',
                   'TL AWD',                      'TSX',
                      'DB9',                   'RAPIDE',
 ...
                  'TOUAREG', 'TOUAREG TDI CLEAN DIESEL',
                      'S60',                  'S60 AWD',
                      'S80',                  'S80 AWD',
                     'XC60',                 'XC60 AWD',
                 'XC70 AWD',                 'XC90 AWD']
Length: 663, dtype: str
------------------------------
Valeurs distinctes pour 'VEHICLECLASS' :
<StringArray>
[                 'COMPACT',              'SUV - SMALL',
                 'MID-SIZE',              'MINICOMPACT',
               'SUBCOMPACT',               'TWO-SEATER',
                'FULL-SIZE',    'STATION WAGON - SMALL',
           'SUV - STANDARD',              'VAN - CARGO',
          'VAN - PASSENGER',  'PICKUP TRUCK - STANDARD',
                  'MINIVAN',  'SPECIAL PURPOSE VEHICLE',
 'STATION WAGON - MID-SIZE',     'PICKUP TRUCK - SMALL']
Length: 16, dtype: str
------------------------------
Valeurs distinctes pour 'TRANSMISSION' :
<StringArray>
['AS5',  'M6', 'AV7', 'AS6',  'A6', 'AM7', 'AV8', 'AS8',  'A7',  'A8',  'M7',
  'A4',  'M5',  'AV',  'A5', 'AM6', 'AS7',  'A9', 'AS9', 'AV6', 'AS4', 'AM5']
Length: 22, dtype: str
------------------------------
Valeurs distinctes pour 'FUELTYPE' :
<StringArray>
['Z', 'D', 'X', 'E']
Length: 4, dtype: str
------------------------------

C:\Users\maelc\AppData\Local\Temp\ipykernel_14124\3877954265.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  variables_qualitatives = df.select_dtypes(include=['object']).columns

### 5) A partir du dataframe, créer un dataframe nommé X composé uniquement des variables suivante : 'ENGINESIZE', 'FUELCONSUMPTION_CITY', 'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB', 'CYLINDERS'

In [ ]:
# A partir du df, Créez une dataframe nommée X composée uniquement des variables :
# 'ENGINESIZE', 'FUELCONSUMPTION_CITY', 'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB', 'CYLINDERS'
X = df[['ENGINESIZE', 'FUELCONSUMPTION_CITY', 'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB', 'CYLINDERS']]
X.head()

,ENGINESIZE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,CYLINDERS
0,2.0,9.9,6.7,8.5,4
1,2.4,11.2,7.7,9.6,4
2,1.5,6.0,5.8,5.9,4
3,3.5,12.7,9.1,11.1,6
4,3.5,12.1,8.7,10.6,6

### 6) Affichez le type de X

In [12]:
# Affichez le type de X
print(type(X))

<class 'pandas.DataFrame'>

### 7) Nommez y la variable 'CO2EMISSIONS' du dataframe

In [13]:
# Nommez y la variable 'CO2EMISSIONS' de df
y = df['CO2EMISSIONS']
y.head()

0    196
1    221
2    136
3    255
4    244
Name: CO2EMISSIONS, dtype: int64

### 8) A partir du dataframe, créez le tableau d'aggrégation suivant : la moyenne des variables 'ENGINESIZE' et 'FUELCONSUMPTION_CITY' en fonction de la variable 'VEHICLECLASS'

In [16]:
agg_df = df.groupby('VEHICLECLASS')[['ENGINESIZE', 'FUELCONSUMPTION_CITY']].mean()
agg_df

                          ENGINESIZE  FUELCONSUMPTION_CITY
VEHICLECLASS
COMPACT                     2.518023             10.915698
FULL-SIZE                   3.931395             14.374419
MID-SIZE                    3.017978             11.535393
MINICOMPACT                 3.078723             11.695745
MINIVAN                     3.407143             14.307143
PICKUP TRUCK - SMALL        3.316667             13.750000
PICKUP TRUCK - STANDARD     4.675806             17.009677
SPECIAL PURPOSE VEHICLE     2.271429             11.571429
STATION WAGON - MID-SIZE    3.383333             11.616667
STATION WAGON - SMALL       2.375000             10.752778
SUBCOMPACT                  3.272308             12.741538
SUV - SMALL                 2.745455             12.090260
SUV - STANDARD              4.380909             16.640000
TWO-SEATER                  3.536620             13.414085
VAN - CARGO                 5.154545             20.881818
VAN - PASSENGER             5.456000             23.228000

### 9) Affichez la consommation moyenne par marque de voiture

In [17]:
conso_par_marque = df.groupby('MAKE')['FUELCONSUMPTION_COMB'].mean()
print(conso_par_marque.sort_values())

MAKE
SMART             6.400000
FIAT              7.810000
MINI              8.197222
MAZDA             8.388889
SCION             8.644444
HONDA             8.857143
VOLKSWAGEN        9.116667
MITSUBISHI        9.150000
HYUNDAI           9.441667
KIA               9.457576
SUBARU            9.782609
ACURA             9.825000
TOYOTA           10.224490
LEXUS            10.713636
BUICK            10.856250
BMW              10.907813
NISSAN           10.930303
JEEP             11.051613
INFINITI         11.161905
PORSCHE          11.211364
VOLVO            11.218182
DODGE            11.784615
AUDI             11.793878
MERCEDES-BENZ    12.115254
CHRYSLER         12.121053
LINCOLN          12.254545
FORD             12.798889
CADILLAC         12.896875
CHEVROLET        13.167442
JAGUAR           13.372727
RAM              13.569231
MASERATI         13.900000
LAND ROVER       14.963158
ASTON MARTIN     15.285714
BENTLEY          15.600000
ROLLS-ROYCE      16.571429
GMC              16.755102
SRT              16.900000
LAMBORGHINI      17.133333
Name: FUELCONSUMPTION_COMB, dtype: float64

### 10) Afficher la voiture la moins poluante (par rapport à la variable CO2EMISSIONS)

In [18]:
# Afficher la voiture la moins poluante (par rapport à la variable CO2EMISSIONS)
voiture_moins_polluante = df.loc[df['CO2EMISSIONS'].idxmin()]
print(voiture_moins_polluante)

MODELYEAR                      2014
MAKE                         TOYOTA
MODEL                       PRIUS c
VEHICLECLASS                COMPACT
ENGINESIZE                      1.5
CYLINDERS                         4
TRANSMISSION                     AV
FUELTYPE                          X
FUELCONSUMPTION_CITY            4.6
FUELCONSUMPTION_HWY             4.9
FUELCONSUMPTION_COMB            4.7
FUELCONSUMPTION_COMB_MPG         60
CO2EMISSIONS                    108
Name: 988, dtype: object